<a href="https://colab.research.google.com/github/ArezooAalipanah/drl_codes/blob/master/numpy_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Intro**
What numpy does? it makes arrays of data (1D, 2D, 3D,...) so we can use these arrays.

https://numpy.org/

## point: why numpy?
python itself has arrays and lists. why should we use numpy instead?
0. mathematical computations are already supported in numpy. while it's harder to do it on lists.
#### 1. its speed.
#### 2. how it uses memory. 

when you make a list in python, say [1, 2, 3] for each element on the list a seperated object is created in the memory and it is saved. 
the list itself gets one seperated place and the objects have another. 
but in arrays (np arrays ) the array is a single object. 
This way reading from that array would also be much faster.
( 28 bytes for every single object, eg.)

# **Array**


In [1]:
import numpy as np

in numpy there is only one type of data and that is array.
every thing in numpy is done through arrays.

https://numpy.org/doc/stable/reference/arrays.html

Array objects
NumPy provides an N-dimensional array type, the ndarray, which describes a collection of **“items” of the same type**. The items can be indexed using for example N integers.

All ndarrays are homogeneous: every item takes up the same size block of memory, and all blocks are interpreted in exactly the same way. How each item in the array is to be interpreted is specified by a separate data-type object, one of which is associated with every array. In addition to basic types (integers, floats, etc.), the data type objects can also represent data structures.

An item extracted from an array, e.g., by indexing, is represented by a Python object whose type is one of the array scalar types built in NumPy. The array scalars allow easy manipulation of also more complicated arrangements of data.


**pay attention to the SAME TYPE**


https://numpy.org/doc/stable/reference/generated/numpy.array.html

numpy.array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, like=None)

In [8]:
sample_array = np.array(1) # for adding the items you can put them inside  []
sample_array2 = np.array([1, 2, 3])

In [9]:
sample_array

array(1)

In [10]:
sample_array2

array([1, 2, 3])

In [11]:
type(sample_array2)

numpy.ndarray

In [12]:
type(sample_array)

numpy.ndarray

In [13]:
"""
np.array([1, 2, 3]) is a 1D array, since it has no depth. 
how to se the dimension:"""
sample_array2.ndim

1

In [14]:
# let's add dimension by 1:
s_array = np.array([
    [1],
    [2],
    [3]
])

In [15]:
s_array.ndim

2

In [16]:
s_array2 = np.array([
    [[1]],
    [[2]]
])

In [17]:
s_array2

array([[[1]],

       [[2]]])

In [18]:
s_array2.ndim


3

In [19]:
# the dim is not the number of items, it's about the depth 
# how many times they are inside. []

In [20]:
# if we don't add any bruckets and give a number directly it is a 0 dim array
sample_array.ndim

0

In [21]:

# so the dim is all about the depth of the bruckets.
s_array3 = np.array([
    [1,2],
    [2,3],
    [3,4],
    [4,4],
    [5,0]
])

In [22]:
s_array3.ndim

2

In [24]:
# now if wanna know about the items and how many they are we use shape
s_array3.shape

(5, 2)

In [25]:
s_array2.shape

(2, 1, 1)

In [26]:
# shape sbows the number of the rows and columns of that array
s_array3
# for example for this (5, 2) means it has 5 rows and 2 columns

array([[1, 2],
       [2, 3],
       [3, 4],
       [4, 4],
       [5, 0]])

In [ ]:
# shape works based on dimensions or axis
 