<a href="https://colab.research.google.com/github/ArezooAalipanah/drl_codes/blob/master/numpy_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Intro**
What numpy does? it makes arrays of data (1D, 2D, 3D,...) so we can use these arrays.

https://numpy.org/

## point: why numpy?
python itself has arrays and lists. why should we use numpy instead?
0. mathematical computations are already supported in numpy. while it's harder to do it on lists.
#### 1. its speed.
#### 2. how it uses memory. 

when you make a list in python, say [1, 2, 3] for each element on the list a seperated object is created in the memory and it is saved. 
the list itself gets one seperated place and the objects have another. 
but in arrays (np arrays ) the array is a single object. 
This way reading from that array would also be much faster.
( 28 bytes for every single object, eg.)

# **Array**


In [1]:
import numpy as np

in numpy there is only one type of data and that is array.
every thing in numpy is done through arrays.

https://numpy.org/doc/stable/reference/arrays.html

Array objects
NumPy provides an N-dimensional array type, the ndarray, which describes a collection of **“items” of the same type**. The items can be indexed using for example N integers.

All ndarrays are homogeneous: every item takes up the same size block of memory, and all blocks are interpreted in exactly the same way. How each item in the array is to be interpreted is specified by a separate data-type object, one of which is associated with every array. In addition to basic types (integers, floats, etc.), the data type objects can also represent data structures.

An item extracted from an array, e.g., by indexing, is represented by a Python object whose type is one of the array scalar types built in NumPy. The array scalars allow easy manipulation of also more complicated arrangements of data.


**pay attention to the SAME TYPE**


https://numpy.org/doc/stable/reference/generated/numpy.array.html

numpy.array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, like=None)

In [2]:
sample_array = np.array(1) # for adding the items you can put them inside  []
sample_array2 = np.array([1, 2, 3])

In [3]:
sample_array

array(1)

In [4]:
sample_array2

array([1, 2, 3])

In [5]:
type(sample_array2)

numpy.ndarray

In [6]:
type(sample_array)

numpy.ndarray

In [7]:
"""
np.array([1, 2, 3]) is a 1D array, since it has no depth. 
how to se the dimension:"""
sample_array2.ndim

1

In [8]:
# let's add dimension by 1:
s_array = np.array([
    [1],
    [2],
    [3]
])

In [9]:
s_array.ndim

2

In [10]:
s_array2 = np.array([
    [[1]],
    [[2]]
])

In [11]:
s_array2

array([[[1]],

       [[2]]])

In [12]:
s_array2.ndim


3

In [13]:
# the dim is not the number of items, it's about the depth 
# how many times they are inside. []

In [14]:
# if we don't add any bruckets and give a number directly it is a 0 dim array
sample_array.ndim

0

In [15]:

# so the dim is all about the depth of the bruckets.
s_array3 = np.array([
    [1,2],
    [2,3],
    [3,4],
    [4,4],
    [5,0]
])

In [16]:
s_array3.ndim

2

In [17]:
# now if wanna know about the items and how many they are we use shape
s_array3.shape

(5, 2)

In [18]:
s_array2.shape

(2, 1, 1)

In [19]:
# shape sbows the number of the rows and columns of that array
s_array3
# for example for this (5, 2) means it has 5 rows and 2 columns

array([[1, 2],
       [2, 3],
       [3, 4],
       [4, 4],
       [5, 0]])

In [20]:
# shape works based on dimensions or axis
""" so in a 1D array we just have axis 0 : shape will send the number of items in axis 0
 in a 2D array axis 0 would count the rows and axis 1 counts the columns.
 same goes for more Ds """
s_array2

array([[[1]],

       [[2]]])

In [21]:
s_array2.shape

(2, 1, 1)

https://numpy.org/doc/stable/reference/arrays.scalars.html
"same type"

In [22]:
# how can we assign the type in numpy?
# You must do it when you are creating the array with dtype

a = np.array([1, 2, 3])

In [23]:
# how to understand what is the dtype when it'a assigned by numpy itself
a.dtype

dtype('int64')

In [24]:
# you can assign other dtypes by your own:
a = np.array([1, 2, 3], dtype=np.uint8)

u for unsigned
and 8 for numbers between 0 and 255

In [25]:
a.dtype


dtype('uint8')

## **Atrributes**

some methods of numpy. basically they are some actions you can do with different arrays.
check the list :
https://numpy.org/doc/stable/reference/generated/numpy.copy.html

In [26]:
arry = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

In [27]:
# size counts to see how many elements are in an array
arry.size

9

In [28]:
arry.shape

(3, 3)

In [29]:
#1.reshape
#  now there is a method called reshape. using it you can change the shape of your array
# pay attention that you should reshape it in a way that the size says the same(makes sense)
# a 3,3 for example can be a 9,1 or a 1,9 ,...

In [30]:
arry.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [31]:
arry.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [32]:
arry.reshape(3,-1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
arry.reshape(2,-1) # but this one gives an error

ValueError: ignored

In [35]:
new_ar= arry.reshape(-1)

In [36]:
new_ar.shape

(9,)

In [38]:
#2. slice
"""
to slice the array or to get the the element with a specific index
"""
arry[0] 

array([1, 2, 3])

In [39]:
# we can also get the items inside the array in the array
arry[0][0]

1

In [40]:
# numpy suggests that instead of opening 2 bruckets, mentioning the row and the column in one brucket
# with a comma
arry[0, 0]


1

In [41]:
# we can also slice it with :
# this would give us a part of it
arry [ 0, 0:]


array([1, 2, 3])

In [43]:
arry[1:, 1]

array([5, 8])

In [45]:
# 3. to attatch 2 arrays together
b_arry = np.array([11, 22, 33])
# vstack method does it vertically
np.vstack((arry, b_arry))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 22, 33]])

In [48]:
# hstack is horizontal
np.hstack((arry, b_arry)) #this one gives an error since the dimensions don't match
# arry is 2D while b_arry is 2D thay can be stacked to the row but to the columns its not possible


ValueError: ignored

In [51]:
c_arry = np.array([[11, 22, 33]])
np.vstack((arry, c_arry))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 22, 33]])

In [53]:
c_arry = np.array([[11, 22, 33]])
np.hstack((arry, c_arry)) #still doesn't work

ValueError: ignored

In [56]:
c_arry = np.array([[11], [22], [33]])
np.hstack((arry, c_arry))

array([[ 1,  2,  3, 11],
       [ 4,  5,  6, 22],
       [ 7,  8,  9, 33]])

In [58]:
# there is another method called concatenate
# it takes the arrays and you can define which axis you want 
# axis 0 or 1,...

np.concatenate((arry, c_arry), axis=1)

array([[ 1,  2,  3, 11],
       [ 4,  5,  6, 22],
       [ 7,  8,  9, 33]])

In [60]:
# there are other methods for splitting the arrays
# vsplit does it verticlly 
np.vsplit(arry, 3) 

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [63]:
np.vsplit(arry, 1) # the number has to be resonable. like you cannot devide 9 by 2

[array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])]

In [64]:
# now the horizonltal
np.hsplit(arry, 3) 

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [66]:
# 4. sort does the sorting
some_arry = np.array([1,4,2])
np.sort(some_arry)

array([1, 2, 4])

In [67]:
# then there is copy and view
# to copy an array :
arry_n = arry.copy()
arry_j = arry.view()

In [68]:
arry_n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
arry_j

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
"""
the difference: copy exactly makes a copy of that array an gives you a new array
but view refers to the exact same array 
so if you make any chnges to the copy, there is no change in the main array 
but if you change the view the main array would change"""
arry_j[0, 1] = 22
arry_n[0, 0] = 2222


In [72]:
arry_n

array([[2222,    2,    3],
       [   4,    5,    6],
       [   7,    8,    9]])

In [73]:
arry_j

array([[ 1, 22,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [74]:
arry

array([[ 1, 22,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [77]:
"""
there might be cases where you have an array that you don't know it's a copy or 
it's a view
you can get it with the base value"""
arry_j.base # it returns the base array

array([[ 1, 22,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [78]:
arry_n.base # it returns nothing because there is no base, it is a complete array itself.


In [80]:
print(arry_n.base)
print(arry_j.base)

None
[[ 1 22  3]
 [ 4  5  6]
 [ 7  8  9]]
